version: "3.9"
services:
  gwscan:
    image: gwscan:${DOCKER_TAG:-latest}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        GODWOKEN_CHAIN: ${GODWOKEN_CHAIN}
        GWSCAN_GRAPHIQL: ${GWSCAN_GRAPHIQL}
        GRAFANA_HOST: ${GRAFANA_HOST}
        GRAFANA_AUTH_TOKEN: ${GRAFANA_AUTH_TOKEN}
        GRAFANA_FOLDER_NAME: ${GRAFANA_FOLDER_NAME}
      target: deploy
    restart: always
    working_dir: /app
    # command: "/app/bin/server"
    command: sh -c "/app/bin/godwoken_explorer eval "GodwokenExplorer.Release.migrate" && /app/bin/server "
    environment:
      - MIX_ENV=prod
      - GODWOKEN_CHAIN
      - GWSCAN_GRAPHIQL
      - GWSCAN_ENDPOINT_HOST
      - GWSCAN_ENDPOINT_PORT
      - GWSCAN_ENDPOINT_SCHEME
      - GWSCAN_ENDPOINT_CHECK_ORIGIN
      - PG_USERNAME
      - PG_PADDWORD
      - PG_DATABASE
      - PG_HOSTNAME
      - PG_PORT
      - PG_POOL_SIZE
      - PG_TIMEOUT
      - PG_CONNECT_TIMEOUT
      - PG_QUEUE_TARGET
      - GODWOKEN_SCAN_ENDPOINT_SECRET_KEY
      - GWSCAN_ENDPOINT_LIVE_VIEW_SIGNING_SALT
      - GWSCAN_BLOCK_SYNC_WORKER_ON_OFF
      - GWSCAN_BLOCK_GLOBAL_STATE_WORKER_ON_OFF
      - GWSCAN_BLOCK_BIND_L1_L2_WORKER_ON_OFF
      - GWSCAN_BLOCK_SYNC_L1_BLOCK_WORKER_ON_OFF
      - GWSCAN_DASHBOARD_USERNAME
      - GWSCAN_DASHBOARD_PASSWORD
      - GODWOKEN_JSON_RPC_URL
      - GODWOKEN_MEMPOOL_RPC_URL
      - CKB_INDEXER_URL
      - CKB_RPC_URL
      - GWSCAN_INTERVAL_SYNC_WORKER
      - GWSCAN_INTERVAL_GLOBAL_STATE_WORKER
      - GWSCAN_INTERVAL_BIND_L1_WORKER
      - GWSCAN_INTERVAL_SYNC_DEPOSITION_WORKER
      - GWSCAN_SENTRY_DSN
      - GWSCAN_SENTRY_ENVIRONMENT_NAME
      - GWSCAN_SENTRY_ENABLE_SOURCE_CODE_CONTEXT
      - GWSCAN_SENTRY_TAGS_ENVIRONMENT
      - GWSCAN_SENTRY_INCLUDED_ENVIRONMENT
      - GWSCAN_SCHEDULER_JOB
      - GWSCAN_MULTIPLE_BLOCK_ONCE
      - GWSCAN_BLOCK_BATCH_SIZE
      - GWSCAN_MULTIPLE_L1_BLOCK_ONCE
      - GWSCAN_L1_BLOCK_BATCH_SIZE
      - SOURCIFY_SERVER_URL
      - SOURCIFY_CHAIN_ID
      - SOURCIFY_REPO_URL
      - GRAFANA_HOST
      - GRAFANA_AUTH_TOKEN
      - GRAFANA_FOLDER_NAME
      - GRAFANA_DATASOURCE_ID
    ports:
      - 4001:4001
      - 9568:9568
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ~/logs_data/gwscan:/etc/logs_data/gwscan/
