name: Register a general contract
description: Required information to register a new general contract
title: '[General Contract] **Contract Name**'
labels:
  - Contract Registration
assignees:
  - Keith-CY
body:

  - type: markdown
    attributes:
      value: "> Verify contract source code on [sourcify](https://sourcify.dev/)"

  - type: input
    id: contract-name
    validations:
      required: true
    attributes:
      label: Contract Name
      description: Identifies the contract.

  - type: input
    id: contract-address
    validations:
      required: true
    attributes:
      label: Contract Address
      description: Contract address of the bridged token on the layer2.

  - type: textarea
    id: constructor-arguments
    validations:
      required: false
    attributes:
      label: Constructor Arguments
      description: ABI-encoded constructor arguments.

  - type: input
    id: compiler-version
    validations:
      required: true
    attributes:
      label: Compiler Version
      description: Compiler version used, e.g v0.8.11+commit.d7f03943

  - type: input
    id: website
    validations:
      required: false
    attributes:
      label: Website
      description: The website of the project for more information.

  - type: input
    id: logo
    validations:
      required: false
    attributes:
      label: Logo URI
      description: The logo of the project to easily recongize.

  - type: textarea
    id: other-info
    validations:
      required: false
    attributes:
      label: Other Info
