name: Deploy to testnet v0
on:
  push:
    branches:
      - "main"

jobs:
  prod-testnet-build-run:
    runs-on: [self-hosted, prod_testnet]
    environment: prod_testnet
    env:
      ENV_FILE_PATH: ${{secrets.ENV_FILE_PATH}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Compose build
        run: docker-compose -f ./docker_compose/gwscan_compose.yml --env-file ${{secrets.ENV_FILE_PATH}} build gwscan

      - name: Docker Compose run
        run: docker-compose -f ./docker_compose/gwscan_compose.yml --env-file ${{secrets.ENV_FILE_PATH}} up -d --force-recreate gwscan

      - name: Clean up unused images
        run: docker image prune -f
