name: Deploy to mainnet v0
on:
  push:
    tags:
      - "v**"

jobs:
  prod-mainnet-build-run:
    runs-on: [self-hosted, prod_mainnet]
    environment: prod_mainnet
    env:
      ENV_FILE_PATH: ${{secrets.ENV_FILE_PATH}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Compose build
        run: docker-compose -f ./docker_compose/gwscan_compose.yml --env-file ${{secrets.ENV_FILE_PATH}} build gwscan

      - name: Docker Compose run
        run: docker-compose -f ./docker_compose/gwscan_compose.yml --env-file ${{secrets.ENV_FILE_PATH}} up -d --force-recreate gwscan

      - name: Clean up unused images
        run: docker image prune -f
