name: Deploy to testnet v1.1
on:
  push:
    branches:
      - "godwoken-v1-testnet-prod"

jobs:
  build:
    uses: ./.github/workflows/build.yml 
    with:
      environment: prod_testnet_v1_1
    secrets: inherit
  deploy-update:
    needs: build
    uses: ./.github/workflows/deploy.yml 
    with:
      k8s-namespace: staging
      k8s-workload: gwscan-api
      image: ${{ needs.build.outputs.image }}
      environment: prod_testnet_v1_1
    secrets: inherit  
