name: gwscan build and run
on:
  push:
    branches:
      - "github-action"
      - "develop"

jobs:
  staging-testnet-build-run:
  build:
    uses: ./.github/workflows/build.yml 
    secrets: inherit
  deploy-update:
    needs: build
    strategy:
      matrix:
        workload: [gwscan-api]
    uses: ./.github/workflows/update-image.yml 
    with:
      k8s-namespace: staging
      k8s-workload: ${{ matrix.workload }}
      image: ${{ needs.build.outputs.image }}
    secrets: inherit
